services:
  icecast:
    image: moul/icecast
    volumes:
    - logs:/var/log/icecast2
    - /etc/localtime:/etc/localtime:ro
    environment:
    - ICECAST_SOURCE_PASSWORD=changeme
    - ICECAST_ADMIN_PASSWORD=changeme
    - ICECAST_PASSWORD=changeme
    - ICECAST_RELAY_PASSWORD=changeme
    - ICECAST_HOSTNAME=noise.example.com
    ports:
    - 8000:8000

volumes:
  logs: